var categorylist = [ // [name]
    ["category.null.name"], //0
    ["category.helmet.name"], //1
    ["category.chestplate.name"], //2
    ["category.leggings.name"], //3
    ["category.boots.name"], //4
    ["category.weapon.name"], //5
    ["category.tool.name"], //6
    ["category.shield.name"], //7
    ["category.accessory.name"], //8
    ["category.gold_food.name"], //9
    ["category.food.name"], //10
    ["category.material.name"], //11
    ["category.event.name"], //12
    ["category.crop.name"], //13
    ["category.plant.name"], //14
    ["category.flower.name"], //15
    ["category.potion.name"], //16
    ["category.block.name"], //17
    ["category.furniture.name"], //18
    ["category.wall.name"], //19
    ["category.usable.name"], //20
    ["category.throwable.name"], //21
    ["category.ranged.name"], //22
    ["category.melee.name"], //23
    ["category.ore.name"], //24
    ["category.bar.name"], //25
    ["category.fish.name"], //26
    ["category.fuel.name"], //27
    ["category.meta.name"], //28
    ["category.unique.name"], //29
    ["category.consumable.name"], //30
    ["category.candy.name"], //31
    ["category.plot.name"], //32
    ["category.special.name"], //33
    ["category.effect.name"], //34
    ["category.debuff.name"], //35
    ["category.buff.name"], //36
    ["category.sticker.name"], //37
    ["category.fs1.name"], //38
    ["category.fs2.name"], //39
    ["category.unobtainable.name"], //40
    ["category.nugget.name"], //41
    ["category.grab_bag.name"], //42
    ["category.scroll.name"], //43
    ["category.upgrade.name"], //44
    ["category.critter.name"], //45
    ["category.powder.name"], //46
    ["category.explosive.name"], //47
    ["category.container.name"], //48
    ["category.fire_type.name"], //49
    ["category.water_type.name"], //50
    ["category.electric_type.name"], //51
    ["category.plant_type.name"], //52
    ["category.ice_type.name"], //53
    ["category.light_type.name"], //54
    ["category.dark_type.name"], //55
    ["category.ammo.name"], //56
    ["category.gem.name"], //57
    ["category.electrum.name"], //58
]