class file {

    constructor(name, type, contents) {
        this.name = name;
        this.type = type;
        this.contents = contents;
        this.hasContents = !(!Array.isArray(contents) || !contents.length);
    }

}

var fileList = [
    new file("1", "folder", [
        new file("logos", "folder", [
            new file("fs1_logo.piko", "piko", [])
        ]),
        new file("allpages.js", "js", []),
        new file("index.html", "html", [])
    ]),
    new file("2", "folder", [
        new file("logos", "folder", [
            new file("fs2_logo.piko", "piko", []),
            new file("fs2_logo.piskel", "piskel", []),
            new file("fs2_logo.png", "png", [])
        ]),
        new file("allpages.js", "js", []),
        new file("index.html", "html", [])
    ]),
    new file("3", "folder", [
        new file("CurrentLogo", "folder", [
            new file("logo.png", "png", [])
        ]),
        new file("logos", "folder", [
            new file("fs3_logo_ace.png", "png", []),
            new file("fs3_logo_ace_cga.png", "png", []),
            new file("fs3_logo_backagain.png", "png", []),
            new file("fs3_logo_cga.png", "png", []),
            new file("fs3_logo_itsback.png", "png", []),
            new file("fs3_logo_kaboom.png", "png", []),
            new file("fs3_logo_newdesign.png", "png", []),
            new file("fs3_logo.piko", "piko", []),
            new file("fs3_logo.piskel", "piskel", []),
            new file("fs3_logo.png", "png", []),
        ]),
        new file("turns", "folder", [
            new file("10s", "folder", [
                new file("turn15.txt", "txt", []),
                new file("turn16.txt", "txt", []),
                new file("turn18.txt", "txt", []),
                new file("turn19_struct.txt", "txt", []),
                new file("turn19.txt", "txt", []),
            ]),
            new file("20s", "folder", [
                new file("turn20.txt", "txt", []),
                new file("turn21.txt", "txt", []),
                new file("turn22.txt", "txt", []),
                new file("turn23.txt", "txt", []),
                new file("turn24.tbgsbb", "tbgsbb", []),
                new file("turn25.tbgsbb", "tbgsbb", []),
                new file("turn26.tbgsbb", "tbgsbb", []),
                new file("turn27.tbgsbb", "tbgsbb", []),
                new file("turn28.tbgsbb", "tbgsbb", []),
                new file("turn29.tbgsbb", "tbgsbb", []),
            ]),
            new file("30s", "folder", [
                new file("turn30.tbgsbb", "tbgsbb", []),
                new file("turn31.tbgsbb", "tbgsbb", []),
                new file("turn32.tbgsbb", "tbgsbb", []),
                new file("turn33.tbgsbb", "tbgsbb", []),
                new file("turn34.tbgsbb", "tbgsbb", []),
                new file("turn35.tbgsbb", "tbgsbb", []),
                new file("turn36.tbgsbb", "tbgsbb", []),
                new file("turn37.tbgsbb", "tbgsbb", []),
                new file("turn38.tbgsbb", "tbgsbb", []),
                new file("turn39.tbgsbb", "tbgsbb", []),
            ]),
            new file("40s", "folder", [
                new file("turn40.tbgsbb", "tbgsbb", []),
                new file("turn41.tbgsbb", "tbgsbb", []),
                new file("turn42.tbgsbb", "tbgsbb", []),
                new file("turn43.tbgsbb", "tbgsbb", []),
                new file("turn44.tbgsbb", "tbgsbb", []),
                new file("turn45.tbgsbb", "tbgsbb", []),
                new file("turn46.tbgsbb", "tbgsbb", []),
                new file("turn47.tbgsbb", "tbgsbb", []),
                new file("turn48.tbgsbb", "tbgsbb", []),
                new file("turn49.tbgsbb", "tbgsbb", []),
            ]),
            new file("50s", "folder", [
                new file("turn50.tbgsbb", "tbgsbb", []),
                new file("turn51.tbgsbb", "tbgsbb", []),
                new file("turn52.tbgsbb", "tbgsbb", []),
                new file("turn53.tbgsbb", "tbgsbb", []),
                new file("turn54.tbgsbb", "tbgsbb", []),
                new file("turn55.tbgsbb", "tbgsbb", []),
                new file("turn56.tbgsbb", "tbgsbb", []),
                new file("turn57.tbgsbb", "tbgsbb", []),
                new file("turn58.tbgsbb", "tbgsbb", []),
                new file("turn59.tbgsbb", "tbgsbb", []),
            ]),
            new file("60s", "folder", [
                new file("turn60.tbgsbb", "tbgsbb", []),
                new file("turn61.tbgsbb", "tbgsbb", []),
                new file("turn62.tbgsbb", "tbgsbb", []),
                new file("turn63.tbgsbb", "tbgsbb", []),
                new file("turn64.tbgsbb", "tbgsbb", []),
                new file("turn65.tbgsbb", "tbgsbb", []),
                new file("turn66.tbgsbb", "tbgsbb", []),
                new file("turn67.tbgsbbp", "tbgsbbp", []),
                new file("turn68.tbgsbbp", "tbgsbbp", []),
                new file("turn69.tbgsbbp", "tbgsbbp", []),
            ]),
            new file("70s", "folder", [
                new file("turn70.tbgsbbp", "tbgsbbp", []),
                new file("turn71.tbgsbbp", "tbgsbbp", []),
                new file("turn72.tbgsbbp", "tbgsbbp", []),
                new file("turn73.tbgsbbp", "tbgsbbp", []),
                new file("turn74.tbgsbbp", "tbgsbbp", []),
                new file("turn75.tbgsbbp", "tbgsbbp", []),
                new file("turn76.tbgsbbp", "tbgsbbp", []),
                new file("turn77.tbgsbbp", "tbgsbbp", []),
                new file("turn78.tbgsbbp", "tbgsbbp", []),
                new file("turn79.tbgsbbp", "tbgsbbp", []),
            ]),
            new file("80s", "folder", [
                new file("turn80.tbgsbbp", "tbgsbbp", []),
                new file("turn81.tbgsbbp", "tbgsbbp", []),
                new file("turn82.tbgsbbp", "tbgsbbp", []),
                new file("turn83.tbgsbbp", "tbgsbbp", []),
                new file("turn84.tbgsbbp", "tbgsbbp", []),
                new file("turn85.tbgsbbp", "tbgsbbp", []),
                new file("turn86.tbgsbbp", "tbgsbbp", []),
                new file("turn87.tbgsbbp", "tbgsbbp", []),
                new file("turn88.tbgsbbp", "tbgsbbp", []),
            ]),
            new file("turnnull.tbgsbbp", "tbgsbbp", []),
        ]), //51
        new file("allpages.js", "js", []),
        new file("archive.html", "html", []),
        new file("archive.js", "js", []),
        new file("banana.gif", "gif", []),
        new file("boilerplate.html", "html", []),
        new file("collapse.js", "js", []),
        new file("contacts.html", "html", []),
        new file("craft_recipe.js", "js", []),
        new file("crafting.html", "html", []),
        new file("creative_inc.js", "js", []),
        new file("creative.html", "html", []),
        new file("garden.js", "js", []),
        new file("gardens.html", "html", []),
        new file("helper.js", "js", []),
        new file("helpers.html", "html", []),
        new file("index.html", "html", []),
        new file("info_page.js", "js", []),
        new file("info.html", "html", []),
        new file("info.js", "js", []),
        new file("inventories.html", "html", []),
        new file("inventory.js", "js", []),
        new file("map.html", "html", []),
        new file("map.js", "js", []),
        new file("mob_plan.png", "png", []),
        new file("mobs.html", "html", []),
        new file("mobs.js", "js", []),
        new file("player_bonuses.txt", "txt", []),
        new file("player_exp_plan.txt", "txt", []),
        new file("popup.js", "js", []),
        new file("potassium.png", "png", []),
        new file("potion_plan.txt", "txt", []),
        new file("quests.html", "html", []),
        new file("quests.js", "js", []),
        new file("settings.html", "html", []),
        new file("settings.js", "js", []),
        new file("sitemap.html", "html", []),
        new file("sitemap.js", "js", []),
        new file("stats_table.js", "js", []),
        new file("stats.html", "html", []),
        new file("struct.js", "js", []),
        new file("structures.html", "html", []),
        new file("tooltip.js", "js", []),
        new file("voting.html", "html", []),
    ]),
    new file("Changelogs", "folder", [
        new file("60s", "folder", [
            new file("turn69.txt", "txt", []),
        ]),
        new file("70s", "folder", [
            new file("turn70.txt", "txt", []),
            new file("turn71.txt", "txt", []),
            new file("turn72.txt", "txt", []),
            new file("turn73.txt", "txt", []),
            new file("turn74.txt", "txt", []),
            new file("turn75.txt", "txt", []),
            new file("turn76.txt", "txt", []),
            new file("turn77.txt", "txt", []),
            new file("turn78.txt", "txt", []),
            new file("turn79.txt", "txt", []),
        ]),
        new file("80s", "folder", [
            new file("turn80.txt", "txt", []),
            new file("turn81.txt", "txt", []),
            new file("turn82.txt", "txt", []),
            new file("turn83.txt", "txt", []),
            new file("turn84.txt", "txt", []),
            new file("turn85.txt", "txt", []),
            new file("turn86.txt", "txt", []),
            new file("turn87.txt", "txt", []),
            new file("turn88.txt", "txt", []),
        ]),
        new file("template.txt", "txt", []),
    ]),
    new file("CSS", "folder", [
        new file("iconsets", "folder", [
            new file("cga.css", "css", []),
            new file("defalt.css", "css", []),
            new file("plastic.css", "css", []),
            new file("resprite.css", "css", []),
        ]),
        new file("mini", "folder", [
            new file("comic_sans.css", "css", []),
            new file("mini_icons.css", "css", []),
            new file("skew_page.css", "css", []),
        ]),
        new file("themes", "folder", [
            new file("ace.css", "css", []),
            new file("cga.css", "css", []),
            new file("light.css", "css", []),
            new file("medium.css", "css", []),
            new file("neon.css", "css", []),
        ]),
        new file("collapse.css", "css", []),
        new file("contacts.css", "css", []),
        new file("icons.css", "css", []),
        new file("main.css", "css", []),
        new file("mob_table.css", "css", []),
        new file("player_table.css", "css", []),
        new file("popup.css", "css", []),
        new file("pt_errata.css", "css", []),
        new file("quests.css", "css", []),
        new file("settings.css", "css", []),
        new file("table.css", "css", []),
        new file("tooltip.css", "css", []),
    ]),
    new file("Icons", "folder", [
        new file("Exported", "folder", [
            new file("alchemy_sheet.png", "png", []),
            new file("ally_sheet.png", "png", []),
            new file("armor_misc_sheet.png", "png", []),
            new file("armor_tiered_sheet.png", "png", []),
            new file("arrow_sheet.png", "png", []),
            new file("block_sheet.png", "png", []),
            new file("cake_sheet.png", "png", []),
            new file("candy_sheet.png", "png", []),
            new file("colorable_sheet.png", "png", []),
            new file("critter_desc_large_sheet.png", "png", []),
            new file("critter_desc_small_sheet.png", "png", []),
            new file("critter_sheet.png", "png", []),
            new file("crop_sheet.png", "png", []),
            new file("decor_sheet.png", "png", []),
            new file("dust_sheet.png", "png", []),
            new file("egg_sheet.png", "png", []),
            new file("file_sheet.png", "png", []),
            new file("fish_sheet.png", "png", []),
            new file("food_sheet.png", "png", []),
            new file("fumo.png", "png", []),
            new file("hr.png", "png", []),
            new file("icons_sheet.png", "png", []),
            new file("info_sheet.png", "png", []),
            new file("mc_modded_sheet1.png", "png", []),
            new file("mc_vanilla_sheet.png", "png", []),
            new file("meat_sheet.png", "png", []),
            new file("mini_sheet.png", "png", []),
            new file("misc_sheet.png", "png", []),
            new file("mob_sheet.png", "png", []),
            new file("mod_equip_sheet.png", "png", []),
            new file("mod_ore_sheet.png", "png", []),
            new file("music_sheet.png", "png", []),
            new file("ore_sheet.png", "png", []),
            new file("placeholder_sheet.png", "png", []),
            new file("plant_sheet.png", "png", []),
            new file("prof_bg_sheet.png", "png", []),
            new file("scroll_sheet.png", "png", []),
            new file("scroll_sheet2.png", "png", []),
            new file("sicons_sheet.png", "png", []),
            new file("sticker_sheet.png", "png", []),
            new file("tags_sheet.png", "png", []),
            new file("text_icon_sheet.png", "png", []),
            new file("weapons_misc_sheet.png", "png", []),
            new file("weapons_tiered_sheet.png", "png", []),
            new file("wood_sheet.png", "png", []),
        ]),
        new file("Exported CGA", "folder", [
            new file("alchemy_sheet.png", "png", []),
            new file("ally_sheet.png", "png", []),
            new file("armor_misc_sheet.png", "png", []),
            new file("armor_tiered_sheet.png", "png", []),
            new file("arrow_sheet.png", "png", []),
            new file("block_sheet.png", "png", []),
            new file("cake_sheet.png", "png", []),
            new file("candy_sheet.png", "png", []),
            new file("colorable_sheet.png", "png", []),
            new file("critter_sheet.png", "png", []),
            new file("crop_sheet.png", "png", []),
            new file("decor_sheet.png", "png", []),
            new file("egg_sheet.png", "png", []),
            new file("file_sheet.png", "png", []),
            new file("fish_sheet.png", "png", []),
            new file("food_sheet.png", "png", []),
            new file("fumo.png", "png", []),
            new file("hr.png", "png", []),
            new file("icons_sheet.png", "png", []),
            new file("info_sheet.png", "png", []),
            new file("mc_vanilla_sheet.png", "png", []),
            new file("meat_sheet.png", "png", []),
            new file("mini_sheet.png", "png", []),
            new file("misc_sheet.png", "png", []),
            new file("mob_sheet.png", "png", []),
            new file("music_sheet.png", "png", []),
            new file("ore_sheet.png", "png", []),
            new file("placeholder_sheet.png", "png", []),
            new file("plant_sheet.png", "png", []),
            new file("prof_bg_sheet.png", "png", []),
            new file("scroll_sheet.png", "png", []),
            new file("sticker_sheet.png", "png", []),
            new file("tags_sheet.png", "png", []),
            new file("text_icon_sheet.png", "png", []),
            new file("weapons_misc_sheet.png", "png", []),
            new file("weapons_tiered_sheet.png", "png", []),
            new file("wood_sheet.png", "png", []),
        ]),
        new file("Exported CGA4", "folder", [
            new file("alchemy_sheet.png", "png", []),
            new file("ally_sheet.png", "png", []),
            new file("block_sheet.png", "png", []),
            new file("cake_sheet.png", "png", []),
            new file("crop_sheet.png", "png", []),
            new file("decor_sheet.png", "png", []),
            new file("file_sheet.png", "png", []),
            new file("fish_sheet.png", "png", []),
            new file("food_sheet.png", "png", []),
            new file("fumo.png", "png", []),
            new file("hr.png", "png", []),
            new file("icons_sheet.png", "png", []),
            new file("info_sheet.png", "png", []),
            new file("misc_sheet.png", "png", []),
            new file("ore_sheet.png", "png", []),
            new file("plant_sheet.png", "png", []),
            new file("prof_bg_sheet.png", "png", []),
            new file("sticker_sheet.png", "png", []),
        ]),
        new file("Original", "folder", [
            new file("alchemy_sheet.piko", "piko", []),
            new file("alchemy_sheet.aesprite", "aesprite", []),
            new file("ally_sheet.piko", "piko", []),
            new file("ally_sheet.aesprite", "aesprite", []),
            new file("armor_misc_sheet.piko", "piko", []),
            new file("armor_tiered_sheet.piko", "piko", []),
            new file("arrow_sheet.piko", "piko", []),
            new file("block_sheet.piko", "piko", []),
            new file("cake_sheet.piko", "piko", []),
            new file("candy_sheet.piko", "piko", []),
            new file("colorable_sheet.piko", "piko", []),
            new file("critter_desc_large_sheet.piko", "piko", []),
            new file("critter_desc_small_sheet.piko", "piko", []),
            new file("critter_sheet.piko", "piko", []),
            new file("crop_sheet.piko", "piko", []),
            new file("decor_sheet.piko", "piko", []),
            new file("dust_sheet.piko", "piko", []),
            new file("egg_sheet.piko", "piko", []),
            new file("file_sheet.piko", "piko", []),
            new file("file_sheet.aesprite", "aesprite", []),
            new file("fish_sheet.piko", "piko", []),
            new file("food_sheet.piko", "piko", []),
            new file("fumo.piko", "piko", []),
            new file("hr.piko", "piko", []),
            new file("icons_sheet.piko", "piko", []),
            new file("info_sheet.piko", "piko", []),
            new file("ink_sheet.piko", "piko", []),
            new file("mc_modded_sheet1.piko", "piko", []),
            new file("mc_vanilla_sheet.piko", "piko", []),
            new file("meat_sheet.piko", "piko", []),
            new file("mini_sheet.piko", "piko", []),
            new file("misc_sheet.piko", "piko", []),
            new file("mob_sheet.piko", "piko", []),
            new file("mod_equip_sheet.piko", "piko", []),
            new file("mod_ore_sheet.piko", "piko", []),
            new file("music_sheet.piko", "piko", []),
            new file("ore_sheet.piko", "piko", []),
            new file("placeholder_sheet.piko", "piko", []),
            new file("plant_sheet.piko", "piko", []),
            new file("prof_bg_sheet.piko", "piko", []),
            new file("prof_bg_sheet.aesprite", "aesprite", []),
            new file("scroll_sheet.piko", "piko", []),
            new file("scroll_sheet2.piko", "piko", []),
            new file("sicons_sheet.piko", "piko", []),
            new file("skill_book_sheet.piko", "piko", []),
            new file("sticker_sheet.piko", "piko", []),
            new file("tags_sheet.piko", "piko", []),
            new file("text_icon_sheet.piko", "piko", []),
            new file("text_icon_sheet.aesprite", "aesprite", []),
            new file("weapons_misc_sheet.piko", "piko", []),
            new file("weapons_tiered_sheet.piko", "piko", []),
            new file("wood_sheet.piko", "piko", []),
        ]),
        new file("Plastic", "folder", [
            new file("alchemy_sheet.png", "png", []),
            new file("ally_sheet.png", "png", []),
            new file("armor_misc_sheet.png", "png", []),
            new file("armor_tiered_sheet.png", "png", []),
            new file("block_sheet.png", "png", []),
            new file("cake_sheet.png", "png", []),
            new file("candy_sheet.png", "png", []),
            new file("colorable_sheet.png", "png", []),
            new file("critter_sheet.png", "png", []),
            new file("crop_sheet.png", "png", []),
            new file("decor_sheet.png", "png", []),
            new file("egg_sheet.png", "png", []),
            new file("file_sheet.png", "png", []),
            new file("fish_sheet.png", "png", []),
            new file("food_sheet.png", "png", []),
            new file("icons_sheet.png", "png", []),
            new file("info_sheet.png", "png", []),
            new file("mc_vanilla_sheet.png", "png", []),
            new file("meat_sheet.png", "png", []),
            new file("mini_sheet.png", "png", []),
            new file("misc_sheet.png", "png", []),
            new file("mob_sheet.png", "png", []),
            new file("music_sheet.png", "png", []),
            new file("ore_sheet.png", "png", []),
            new file("placeholder_sheet.png", "png", []),
            new file("plant_sheet.png", "png", []),
            new file("prof_bg_sheet.png", "png", []),
            new file("scroll_sheet.png", "png", []),
            new file("sticker_sheet.png", "png", []),
            new file("tags_sheet.png", "png", []),
            new file("weapons_misc_sheet.png", "png", []),
            new file("weapons_tiered_sheet.png", "png", []),
            new file("wood_sheet.png", "png", []),
        ]),
        new file("Resprite", "folder", [
            new file("alchemy_sheet.png", "png", []),
            new file("armor_tiered.png", "png", []),
            new file("block_sheet.png", "png", []),
            new file("crop_sheet.png", "png", []),
            new file("dust_sheet.png", "png", []),
            new file("equip_sheet_plan.png", "png", []),
            new file("food_sheet.png", "png", []),
            new file("icons_sheet.png", "png", []),
            new file("mc_vanilla_sheet.png", "png", []),
            new file("misc_sheet.png", "png", []),
            new file("ore_sheet.png", "png", []),
            new file("placeholder_sheet.png", "png", []),
            new file("weapons_tiered_sheet.png", "png", []),
            new file("wood_sheet.png", "png", []),
        ]),
        new file("Resprite Original", "folder", [
            new file("alchemy_sheet.piko", "piko", []),
            new file("armor_tiered.piko", "piko", []),
            new file("block_sheet.piko", "piko", []),
            new file("crop_sheet.piko", "piko", []),
            new file("dust_sheet.piko", "piko", []),
            new file("equip_sheet_plan.piko", "piko", []),
            new file("food_sheet.piko", "piko", []),
            new file("icons_sheet.piko", "piko", []),
            new file("icons_sheet.aesprite", "aesprite", []),
            new file("mc_vanilla_sheet.piko", "piko", []),
            new file("misc_sheet.piko", "piko", []),
            new file("ore_sheet.piko", "piko", []),
            new file("placeholder_sheet.piko", "piko", []),
            new file("type_resprite_big.piskel", "piskel", []),
            new file("weapons_tiered_sheet.piko", "piko", []),
            new file("wood_sheet.piko", "piko", []),
        ]),
        new file("Text", "folder", [
            new file("coin.png", "png", []),
            new file("decicoin.png", "png", []),
            new file("dollar_bill.png", "png", []),
            new file("phone.png", "png", []),
            new file("ruby.png", "png", []),
            new file("fs_site.png", "png", []),
            new file("gsheet.png", "png", []),
            new file("tumblr.png", "png", []),
            new file("tvtropes.png", "png", []),
            new file("wasteof.png", "png", []),
            new file("wiki.png", "png", []),
            new file("youtube.png", "png", []),
        ]),
        new file("monocle.png", "png", []),
        new file("Screenshot 2021-12-26 214726.png", "png", []),
        new file("spyglass_platform.png", "png", []),
    ]),
    new file("js_lists", "folder", [
        new file("archiveList.js", "js", []),
        new file("categoryList.js", "js", []),
        new file("cropList.js", "js", []),
        new file("effectList.js", "js", []),
        new file("eggList.js", "js", []),
        new file("equipList.js", "js", []),
        new file("equipList2.js", "js", []),
        new file("fileList.js", "js", []),
        new file("futureItemList.js", "js", []),
        new file("headerLinks.js", "js", []),
        new file("helpList.js", "js", []),
        new file("mobList.js", "js", []),
        new file("recipeList.js", "js", []),
        new file("replaceList.js", "js", []),
        new file("settingsList.js", "js", []),
        new file("skillList.js", "js", []),
        new file("skillRewards.js", "js", []),
        new file("splashList.js", "js", []),
        new file("typeList.js", "js", []),
        new file("userData.js", "js", []),
    ]),
    new file("lang", "folder", [
        new file("en_us.json", "json", []),
        new file("es_es.json", "json", []),
    ]),
    new file("Maps", "folder", [
        new file("FullMap_T61_CGA.png", "png", []),
        new file("FullMap_T61.png", "png", []),
    ]),
    new file("music", "folder", [
        new file("fsnap", "folder", [
            new file("Exported", "folder", [
                new file("day1.wav", "wav", []),
                new file("day2.wav", "wav", []),
                new file("menu.wav", "wav", []),
                new file("night1.wav", "wav", []),
                new file("night3.wav", "wav", []),
            ]),
            new file("Original", "folder", [
                new file("day1.flp", "flp", []),
                new file("day2.flp", "flp", []),
                new file("menu.flp", "flp", []),
                new file("night1.flp", "flp", []),
                new file("night3.flp", "flp", []),
            ]),
        ]),
    ]),
    new file("Snap!", "folder", [
        new file("builds", "folder", [
            new file("build 0.xml", "xml", []),
        ]),
        new file("logos", "folder", [
            new file("logo_cga.png", "png", []),
            new file("logo_plastic.png", "png", []),
            new file("logo.png", "png", []),
        ]),
        new file("music images", "folder", [
            new file("island of stone.png", "png", []),
            new file("night's third.png", "png", []),
            new file("short and sweet.png", "png", []),
            new file("snappy menu.png", "png", []),
            new file("stars of sky.png", "png", []),
        ]),
    ]),
    new file("sound", "folder", [
        new file("popup", "folder", [
            new file("box.wav", "wav", []),
            new file("paper.wav", "wav", []),
        ]),
    ]),
    new file("_D__Personal_TBGs_Websites_FightSim_3_creative.html.piko", "piko", []),
    new file("common_allpages.js", "js", []),
    new file("credits.txt", "txt", []),
    new file("electrum.txt", "txt", []),
    new file("favicon.ico", "ico", []),
    new file("fightsim-6px.ttf", "ttf", []),
    new file("fightsim-12px.ttf", "ttf", []),
    new file("fightsim-12px-bold.ttf", "ttf", []),
    new file("fightsim-20px-italic.ttf", "ttf", []),
    new file("fightsim-20px.ttf", "ttf", []),
    new file("fightsim-body-bold-double.ttf", "ttf", []),
    new file("fightsim-body-bold-italic.ttf", "ttf", []),
    new file("fightsim-body-bold.ttf", "ttf", []),
    new file("fightsim-body-italic.ttf", "ttf", []),
    new file("fightsim-body-mono.ttf", "ttf", []),
    new file("fightsim-body.ttf", "ttf", []),
    new file("fightstack.ttf", "ttf", []),
    new file("fs_logo.png", "png", []),
    new file("get_no_texture_items.txt", "txt", []),
    new file("golden.txt", "txt", []),
    new file("index.html", "html", []),
    new file("root_allpages.js", "js", []),
]   