var replaceList = { // "name": [inputs, parse inside?, [bbcode, markdown, html]] (use %1, %2, etc. for inputs)
    // single tags
    "hr": [0, true, ["[img alt=Horizontal rule]https://realicraft.github.io/FightSim/Icons/Exported/hr.png[/img]", "![Horizontal Rule](https://realicraft.github.io/FightSim/Icons/Exported/hr.png)", "<img src=\"https://realicraft.github.io/FightSim/Icons/Exported/hr.png\" alt=\"Horizontal Rule\"/>"]],
    "hr2": [0, true, ["[hr]", "---", "<hr>"]],
    "br": [0, true, ["[br]", "\n", "<br>"]],
    "links": [0, true, [
        "[url=https://realicraft.github.io/FightSim/3/]Website[/url] [url=https://fightsim.miraheze.org/wiki/Main_Page]Wiki[/url] [url=https://forms.gle/VtpwBew9qHj1NcUt9]Disp. Phone Submission Form[/url] [url=https://wasteof.money/users/fightsim3]Official wasteof account[/url]",
        "[Website](https://realicraft.github.io/FightSim/3/) [Wiki](https://fightsim.miraheze.org/wiki/Main_Page) [Disp. Phone Submission Form](https://forms.gle/VtpwBew9qHj1NcUt9) [Official wasteof account](https://wasteof.money/users/fightsim3)",
        "<a href=\"https://realicraft.github.io/FightSim/3/\">Website</a> <a href=\"https://fightsim.miraheze.org/wiki/Main_Page\">Wiki</a> <a href=\"https://forms.gle/VtpwBew9qHj1NcUt9\">Disp. Phone Submission Form</a> <a href=\"https://wasteof.money/users/fightsim3\">Official wasteof account</a>"
    ]],
    "coi": [0, true, ["[img alt=Coin]https://realicraft.github.io/FightSim/Icons/Text/coin.png[/img]", "![Coin](https://realicraft.github.io/FightSim/Icons/Text/coin.png)", "<img src=\"https://realicraft.github.io/FightSim/Icons/Text/coin.png\" alt=\"Coin\"/>"]],
    "dec": [0, true, ["[img alt=Decicoin]https://realicraft.github.io/FightSim/Icons/Text/decicoin.png[/img]", "![Decicoin](https://realicraft.github.io/FightSim/Icons/Text/decicoin.png)", "<img src=\"https://realicraft.github.io/FightSim/Icons/Text/decicoin.png\" alt=\"Decicoin\"/>"]],
    "dol": [0, true, ["[img alt=Dollar Bill]https://realicraft.github.io/FightSim/Icons/Text/dollar_bill.png[/img]", "![Dollar Bill](https://realicraft.github.io/FightSim/Icons/Text/dollar_bill.png)", "<img src=\"https://realicraft.github.io/FightSim/Icons/Text/dollar_bill.png\" alt=\"Dollar Bill\"/>"]],
    "rub": [0, true, ["[img alt=Ruby]https://realicraft.github.io/FightSim/Icons/Text/ruby.png[/img]", "![Ruby](https://realicraft.github.io/FightSim/Icons/Text/ruby.png)", "<img src=\"https://realicraft.github.io/FightSim/Icons/Text/ruby.png\" alt=\"Ruby\"/>"]],
    "pho": [0, true, ["[img alt=Phone]https://realicraft.github.io/FightSim/Icons/Text/phone.png[/img]", "![Phone](https://realicraft.github.io/FightSim/Icons/Text/phone.png)", "<img src=\"https://realicraft.github.io/FightSim/Icons/Text/phone.png\" alt=\"Phone\"/>"]],
    "needcite": [0, true, [
        "[sup][[i][url=\"https://en.wikipedia.org/wiki/Wikipedia:Citation_needed\"]citation needed[/url][/i]][/sup]",
        "[*[citation needed](https://en.wikipedia.org/wiki/Wikipedia:Citation_needed)*]",
        "<sup>[<i><a href=\"https://en.wikipedia.org/wiki/Wikipedia:Citation_needed\">citation needed</a></i>]</sup>"
    ]],
    // bbcode tags
    "b": [1, true, ["[b]%1[/b]", "**%1**", "<b>%1</b>"]],
    "i": [1, true, ["[i]%1[/i]", "*%1*", "<i>%1</i>"]],
    "u": [1, true, ["[u]%1[/u]", "%1", "<u>%1</u>"]],
    "s": [1, true, ["[s]%1[/s]", "~~%1~~", "<s>%1</s>"]],
    "*": [1, true, ["[li]%1[/li]", "- %1", "<li>%1</li>"]],
    "bi": [1, true, ["[b][i]%1[/i][/b]", "***%1***", "<b><i>%1</b></i>"]],
    "sup": [1, true, ["[sup]%1[/sup]", "%1", "<sup>%1</sup>"]],
    "sub": [1, true, ["[sub]%1[/sub]", "%1", "<sub>%1</sub>"]],
    "code": [1, false, ["[code]%1[/code]", "```\n%1\n```", "<code style=\"display: block\">%1</code>"]],
    "list": [1, true, ["[list]%1[/list]", "%1", "<ul>%1</ul>"]],
    "nlist": [1, true, ["[list type=decimal]%1[/list]", "%1", "<ol>%1</ol>"]],
    "pre": [1, false, ["[pre]%1[/pre]", "```\n%1\n```", "<pre>%1</pre>"]],
    "ruby": [2, true, ["[ruby=%2]%1[/ruby]", "%1", "<ruby>%1<rt>%2</rt></ruby>"]],
    "purl": [1, true, ["[url]%1[/url]", "[%1](%1)", "<a href=\"%1\">%1</a>"]],
    "url": [2, true, ["[url=%1]%2[/url]", "[%1](%2)", "<a href=\"%1\">%2</a>"]],
    // specific tags
    "green": [1, true, ["[color=green]%1[/color]", "%1", "<span style=\"color: green\">%1</span>"]],
    "red": [1, true, ["[color=red]%1[/color]", "%1", "<span style=\"color: red\">%1</span>"]],
    "crhit": [1, true, ["[color=green][b]%1[/b][/color]", "**%1**", "<span style=\"color: green\"><b>%1</b></span>"]],
    "crmiss": [1, true, ["[color=red][b]%1[/b][/color]", "*%1***", "<span style=\"color: red\"><b>%1</b></span>"]],
    "phone": [1, true, ["[img]https://realicraft.github.io/FightSim/Icons/Text/phone.png[/img][color=#0f5f0f]%1[/color]", "![](https://realicraft.github.io/FightSim/Icons/Text/phone.png)%1", "<img src=\"https://realicraft.github.io/FightSim/Icons/Text/phone.png\" alt=\"\"/><span style=\"color: #0f5f0f\">%1</span>"]],
    "comment": [1, true, ["([color=transparent]%1[/color])", "", "(<span style=\"color: transparent\">%1</span>)"]], // md intentionally left blank
    "frac": [2, true, ["[sup]%1[/sup]/[sub]%2[/sub]", "%1/%2", "<sup>%1</sup>/<sub>%1</sub>"]],
    // fonts
    "small": [1, true, ["[size=1]%1[/size]", "%1", "<span style=\"font-size: 0.7em\">%1</span>"]],
    "normal": [1, true, ["[size=2]%1[/size]", "%1", "<span style=\"font-size: 1em\">%1</span>"]],
    "large": [1, true, ["[size=3]%1[/size]", "%1", "<span style=\"font-size: 1.35em\">%1</span>"]],
    "larger": [1, true, ["[size=4]%1[/size]", "%1", "<span style=\"font-size: 1.45em\">%1</span>"]],
    "massive": [1, true, ["[size=5]%1[/size]", "%1", "<span style=\"font-size: 2em\">%1</span>"]],
    "gigantic": [1, true, ["[size=6]%1[/size]", "%1", "<span style=\"font-size: 2.65em\">%1</span>"]],
    "extreme": [1, true, ["[size=7]%1[/size]", "%1", "<span style=\"font-size: 3.95em\">%1</span>"]],
    "arial": [1, true, ["[font=Arial]%1[/font]", "%1", "<span style=\"font-family: Arial\">%1</span>"]],
    "comicsans": [1, true, ["[font=Comic Sans MS]%1[/font]", "%1", "<span style=\"font-family: Comic Sans MS\">%1</span>"]],
    "courier": [1, true, ["[font=Courier New]%1[/font]", "%1", "<span style=\"font-family: Courier New\">%1</span>"]],
    "impact": [1, true, ["[font=Impact]%1[/font]", "%1", "<span style=\"font-family: Impact\">%1</span>"]],
    "times": [1, true, ["[font=Times New Roman]%1[/font]", "%1", "<span style=\"font-family: Times New Roman\">%1</span>"]],
    "trebuche": [1, true, ["[font=Trebuche MS]%1[/font]", "%1", "<span style=\"font-family: Trebuche MS\">%1</span>"]],
    "verdana": [1, true, ["[font=Verdana]%1[/font]", "%1", "<span style=\"font-family: Verdana\">%1</span>"]],
    "wingdings": [1, true, ["[font=Wingdings]%1[/font]", "%1", "<span style=\"font-family: Wingdings\">%1</span>"]],
    "size": [2, true, ["[size=%1em]%2[/font]", "%2", "<span style=\"font-size: %1em\">%2</span>"]],
    "color": [2, true, ["[color=%1]%2[/font]", "%2", "<span style=\"color: %1\">%2</span>"]],
    // tables
    "table": [1, true, ["[table]%1[/table]", "%1", "<table>%1</table>"]],
    "tr": [1, true, ["[tr]%1[/tr]", "%1", "<tr>%1</tr>"]],
    "td": [1, true, ["[td]%1[/td]", "%1", "<td>%1</td>"]],
    // quotes
    "quote": [1, true, ["[quote]%1[/quote]", "[Quote]\n%1\n[End quote]", "<blockquote>%1</blockquote>"]],
    "quoteauth": [2, true, ["[quote=%1]%2[/quote]", "[Quote from %1]\n%2\n[End quote]", "<blockquote><cite>Quote from %1:</cite><br/>%2</blockquote>"]],
    "quoteall": [4, true, ["[quote author=%1 link=msg=%2 date=%3]%4[/quote]", "[[Quote from %1](https://tbgforums.com/forums/index.php?msg=%2)]\n%4\n[End quote]", "<blockquote><a href=\"https://tbgforums.com/forums/index.php?msg=%2\"><cite>Quote from %1:</cite></a><br/>%4</blockquote>"]],
    // wiki link
    "wiki": [1, true, ["[i][[%1]][/i]", "*\\[\\[%1]]*", "<i>[[%1]]</i>"]],
    // esolang output
    "esocode": [1, false, ["[pre][color=green]%1[/color][/pre]", "```\n%1\n```", "<pre><span style\"color: green\">%1</span></pre>"]],
    "esooutput": [1, false, ["[pre][color=#002f00]%1[/color][/pre]", "```\n%1\n```", "<pre><span style\"color: #002f00\">%1</span></pre>"]],
    "esowarn": [1, false, ["[pre][color=red]%1[/color][/pre]", "```\n%1\n```", "<pre><span style\"color: red\">%1</span></pre>"]],
    "esoerror": [1, false, ["[pre][color=red][b]%1[/b][/color][/pre]", "```\n%1\n```", "<pre><span style\"color: red\"><b>%1</b></span></pre>"]],
    // types
    "normal": [1, true, ["[color=#5f5f5f]%1[/color]", "%1", "<span style\"color: #5f5f5f\">%1</span>"]],
    "fire": [1, true, ["[color=#4f0f0f]%1[/color]", "%1", "<span style\"color: #4f0f0f\">%1</span>"]],
    "water": [1, true, ["[color=#0f0f5f]%1[/color]", "%1", "<span style\"color: #0f0f5f\">%1</span>"]],
    "elec": [1, true, ["[color=#4f4f0f]%1[/color]", "%1", "<span style\"color: #4f4f0f\">%1</span>"]],
    "plant": [1, true, ["[color=#0f4f0f]%1[/color]", "%1", "<span style\"color: #0f4f0f\">%1</span>"]],
    "ice": [1, true, ["[color=#0f4f4f]%1[/color]", "%1", "<span style\"color: #0f4f4f\">%1</span>"]],
    "light": [1, true, ["[color=#5f5f1f]%1[/color]", "%1", "<span style\"color: #5f5f1f\">%1</span>"]],
    "dark": [1, true, ["[color=#1f1f4f]%1[/color]", "%1", "<span style\"color: #1f1f4f\">%1</span>"]],
    // players
    "reali": [1, true, ["[color=#5f4f0f][b]Reali[/b]: %1[/color]", "**Reali**: %1", "<span style\"color: #5f4f0f\"><b>Reali</b>: %1</span>"]],
    "incend": [1, true, ["[color=#5f2f0f][b]Incendiary[/b]: %1[/color]", "**Incendiary**: %1", "<span style\"color: #5f2f0f\"><b>Incendiary</b>: %1</span>"]],
    "byron": [1, true, ["[color=#3f1f0f][b]Byron[/b]: %1[/color]", "**Byron**: %1", "<span style\"color: #3f1f0f\"><b>Byron</b>: %1</span>"]],
    "sparky": [1, true, ["[color=#6f5f0f][b]Sparky[/b]: %1[/color]", "**sparky**: %1", "<span style\"color: #6f5f0f\"><b>Sparky</b>: %1</span>"]],
    "soli": [1, true, ["[color][b]Solitaire[/b]: %1[/color]", "**Solitaire**: %1", "<b>Solitaire</b>: %1"]],
    "fares": [1, true, ["[color=#0f3f0f][b]Faressain[/b]: %1[/color]", "**Faressain**: %1", "<span style\"color: #0f3f0f\"><b>Faressain</b>: %1</span>"]],
    "gilb": [1, true, ["[color][b]Gilbert[/b]: %1[/color]", "**Gilbert**: %1", "<b>Gilbert</b>: %1"]],
    "twi": [1, true, ["[color=#4f0f4f][b]Twilight[/b]: %1[/color]", "**Twilight**: %1", "<span style\"color: #4f0f4f\"><b>Twilight</b>: %1</span>"]],
    "luigi": [1, true, ["[color=#0f5f0f][b]Luigi[/b]: %1[/color]", "**Luigi**: %1", "<span style\"color: #0f5f0f\"><b>Lugig</b>: %1</span>"]],
    "kitty": [1, true, ["[color=#3f0f3f][b]Kitty[/b]: %1[/color]", "**Kitty**: %1", "<span style\"color: #3f0f3f\"><b>Kitty</b>: %1</span>"]],
    "savvy": [1, true, ["[color][b]Savvy[/b]: %1[/color]", "**Savvy**: %1", "<b>Savvy</b>: %1"]],
    "bobby": [1, true, ["[color][b]Bobby[/b]: %1[/color]", "**Bobby**: %1", "<b>Bobby</b>: %1"]],
    "tony": [1, true, ["[color=#2f1f00][b]Tony[/b]: %1[/color]", "**Tony**: %1", "<span style\"color: #2f1f00\"><b>Tony</b>: %1</span>"]],
    "landon": [1, true, ["[color][b]Landon[/b]: %1[/color]", "**Landon**: %1", "<b>Landon</b>: %1"]],
    // npcs
    "laurie": [1, true, ["[color=#5f0f5f][b]Laurie[/b]: %1[/color]", "**Laurie**: %1", "<span style\"color: #5f0f5f\"><b>Laurie</b>: %1</span>"]],
    "morshu": [1, true, ["[color=#5f2f0f][b]Morshu[/b]: %1[/color]", "**Morshu**: %1", "<span style\"color: #5f2f0f\"><b>Morshu</b>: %1</span>"]],
    "hank": [1, true, ["[color=#5f0f0f][b]Hank[/b]: %1[/color]", "**Hank**: %1", "<span style\"color: #5f0f0f\"><b>Hank</b>: %1</span>"]],
    "sans": [1, true, ["[b]Sans[/b]: [font=Comic Sans MS]%1[/font]", "**Sans**: %1", "<b>Sans</b>: <span style\"font-family: Comic Sans MS\">%1</span>"]],
    // wiki links
    "tbgw": [2, true, ["[i][[[url=https://tbgs.miraheze.org/wiki/%1]%2[/url]]][/i]", "*\\[\\[[%2](https://tbgs.miraheze.org/wiki/%1)]]*", ""]],
    "fsw": [2, true, ["[i][[[url=https://fightsim.miraheze.org/wiki/%1]%2[/url]]][/i]", "*\\[\\[[%2](https://fightsim.miraheze.org/wiki/%1)]]*", ""]],
}