var splashesList = { // "type": [splash, ...]
    "always": [
        "Not at all dragon free!",
        "Contains a few nuts.",
        "No polygons!",
        "Static letters!",
        "One spin-off!",
        "May contain spiders.",
        "Reticulating splines...",
        "Bars!",
        "Open Source!",
        "Pixels!",
        "In English!",
        "¡En español!",
        "Punch everything!",
        "Some of these are useful!",
        "20 GOTO 10",
        "Slimes!",
        "Allies!",
        "Phones!",
        "...?",
        // "slime :)", // maybe not now
        "Loading...",
        "Structures!",
        // "ft. Slime",
        "No kitchen sink!",
        "<i>Italic!</i>",
        "<b>Bold!</b>",
        "Should not be played while driving!",
        "Bottle o' Water!",
        "No music!",
        "Hardite!",
        "Hrmm.",
        "Lapis! Nope, diamonds.",
        "Filled with lore!",
        "Dyes!",
        "Filled with ores!",
    ],
    "monday": [
        "Monday funday",
        "lasagna",
    ],
    "tuesday": [
        "it's chewsday innit",
        "two's day",
        "Taco Tuesday!",
    ],
    "wednesday": [
        "no camels :(",
        "hump day",
    ],
    "thursday": [
        "i can't think of a good thursday splash",
    ],
    "friday": [
        "happy friday",
        "gettin' freaky on a friday night",
        "gettin' freaky on a friday night, yeah",
        "Taco Tuesday! (on a friday)",
        "pico funny -- pico funny",
        "yoooooooooooo",
        "ooh-yeah-ah ah",
    ],
    "saturday": [
        "caturday",
        "have a good weekend",
    ],
    "sunday": [
        "have a good weekend",
        "Sunday sundae",
    ],
    "rare": [
        "So how's your day been going?",
        "hi",
        "hola",
        "Peter Griffin",
        "Also try Minceraft!",
        "Isn't it weird how most bots on the TBGs were named after elements?",
        "§oItalic!",
        "\"Look at the baby dragon\", they said. \"It'll be fine\", they said.",
        "& Knuckles",
        "Funny splash text.",
        "missingno.",
        "<span class='icon night_vision'></span> <span class='icon night_vision'></span>",
        "Aw, what a cute baby drag- <b>oh.</b>",
        "No one is dead! Let's <a href='https://tbgforums.com/forums/index.php?topic=6518.0'>keep it</a> that way, alright?<br /><br />Unless you count Luigi.",
        "furfrou",
        "Very quiet birdwatcher",
        "Cheeeeeese *-*",
        "43.250.142.151       tbgforums.com",
    ],
    "new years": [
        "Happy New Year's!",
        "new year same game",
        "don't forget to verify your y2k compliance",
    ],
    "valentines": [
        "Happy Valentine's day!",
        "heart-shaped chocolate",
    ],
    "easter": [
        "Happy Easter!",
        "but where'd the eggs come from",
    ],
    "april fools": [
        "<span style='color:var(--rarity_unique);font-size:300%'>APRIL FOOLS!</span>",
    ],
    "birthday": [
        "make sure to say happy birthday",
        "i am getting older",
    ],
    "halloween": [
        "Happy Halloween!",
        "so what are you dressing up as?",
        "ooga booga",
        "<span style='font-size:300%'>BOO!</span>",
    ],
    "thanksgiving": [
        "Happy Thanksgiving!",
        "don't forget the cranberry sauce",
    ],
    "christmas": [
        "Merry Christmas!",
        "did you remember to leave out milk and cookies?",
        "santa time"
    ],
    "also try": [
        "Also try <i>Minecraft</i>!",
        "Also try <i>Terraria</i>!",
        "Also try <i>Stardew Valley</i>!",
        "Also try <i>Team Fortress 2</i>!",
        "Also try <i>Legends of Idleon</i>!",
        "Also try <i>Kingdom of Loathing</i>!",
        "Also try <i>Cookie Clicker</i>!",
        "Also try <i>Item Asylum</i>!",
        "Also try <i>Friday Night Funkin'</i>!",
        "Also try <i>Deltarune</i>!",
        "Also try <i>Mineycraftia</i>!",
        "Also try <i>Fragmented Future</i>!",
        "Also try <i>the role play</i>!",
        "Also try <em>literally</em> any other RPG on this forum",
        "No TVTropes page! (yet)",
        "Check out <a href='https://fightsim.miraheze.org/wiki/Main_Page'>the wiki</a>!",
        "Check out <a href='https://shefwerld.github.io/shefnews/index.html'>SKNN</a>!",
        // "Try out Nihonium!", // this is a real backwards-incompatibility moment
        // "Try out Lithium!", // rip
        /* "Try out Flerovium!",
        "Try out Nickel!",
        "Try out Platinum!",*/
        "Try out Trendy!",
        /* "Try out CABS!",*/
    ],
    "ideas": [
        "If you need ideas, have you tried casting a spell you don't know?",
        "If you need ideas, have you tried blowing something up?",
        "If you need ideas, have you tried punching someone?",
        "If you need ideas, have you tried stealing someone's chocolate?",
        "If you need ideas, have you tried reading the Quests page?",
        "If you need ideas, have you tried looking at your Inventory?",
        "If you need ideas, have you tried rereading the thread?",
        "If you need ideas, have you tried reading the wiki?",
        "If you need ideas, have you tried proceeding?",
        "If you need ideas, have you tried committing murder?",
        "If you need ideas, have you tried spading?",
        "If you need ideas, have you tried trying to figure out what that scroll does?",
        "If you need ideas, have you tried doing something random?",
        "If you need ideas, have you tried doing something stupid?",
        "If you need ideas, have you tried making funny beeping noises?",
        "If you need ideas, have you tried playing Minecraft?",
        "If you need ideas, have you tried making a machine to thrash your own ass?",
    ]
}